<%@ page import="lk.ijse.ecommerce.dto.categoryDTO" %>
<%@ page import="java.util.List" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Category Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container my-4">
    <!-- Add Category Form -->
    <div class="card mb-4">
        <div class="card-header">Add New Category</div>
        <div class="card-body">
            <!-- Important: Add enctype and correct servlet mapping -->
            <form id="categoryForm" action="Category" method="post" enctype="multipart/form-data"><!-- Category Name -->
                <div class="mb-3">
                    <label for="name" class="form-label">Category Name</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <!-- Category Description -->
                <div class="mb-3">
                    <label for="description" class="form-label">Category Description</label>
                    <textarea class="form-control" id="description" name="description" rows="3" required></textarea>
                </div>
                <!-- Category Image -->
                <div class="mb-3">
                    <label for="image" class="form-label">Category Image</label>
                    <input type="file" class="form-control" id="image" name="categoryImage" accept="image/*" required>
                    <small class="text-muted">Maximum file size: 5MB. Supported formats: JPG, PNG, GIF</small>
                </div>
                <!-- Submit Button -->
                <button type="submit" class="btn btn-success">Add Category</button>
            </form>
        </div>
    </div>
    <!-- Category List -->
    <%
        List<categoryDTO> dataList = (List<categoryDTO>) request.getAttribute("categoryList");
        if (dataList != null && !dataList.isEmpty()) {
    %>
    <h2>Category List</h2>
    <table class="table table-striped">
        <thead class="table-dark">
        <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>Description</th>
            <th>Image</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <%
            for (categoryDTO categoryDTO : dataList) {
        %>
        <%-- Example row (dynamic content should be generated by the servlet or backend logic) --%>
        <tr>
            <td><%=categoryDTO.getCategoryId() %></td>
            <td><%=categoryDTO.getName() %></td>
            <td><%=categoryDTO.getDescription() %></td>
            <td>
                <img src="<%= categoryDTO.getImage() %>" alt="<%= categoryDTO.getImage() %>" style="width: 100px; height: auto;">
            </td>
            <td>
                <!-- Edit Button Triggers Modal -->
                <button
                        class="btn btn-sm btn-warning edit-btn"
                        data-bs-toggle="modal"
                        data-bs-target="#editModal"
                        data-id="<%= categoryDTO.getCategoryId() %>"
                        data-name="<%= categoryDTO.getName() %>"
                        data-description="<%= categoryDTO.getDescription() %>"
                        data-image="<%= categoryDTO.getImage() %>">
                    Edit
                </button>
                <a href="CategoryServlet?action=delete&id=1" class="btn btn-sm btn-danger">Delete</a>
            </td>
        </tr>
        <%
            }
        %>
        <%-- Add dynamic rows here from the backend --%>
        </tbody>
        <%
            }
        %>
    </table>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit Category</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Important: Add enctype and correct servlet mapping -->
                <form action="categoryUpdate" method="post" >
                    <input type="hidden" id="modal-category-id" name="id">

                    <!-- Category Name -->
                    <div class="mb-3">
                        <label for="modal-category-name" class="form-label">Category Name</label>
                        <input type="text" class="form-control" id="modal-category-name" name="name" required>
                    </div>

                    <!-- Category Description -->
                    <div class="mb-3">
                        <label for="modal-category-description" class="form-label">Category Description</label>
                        <textarea class="form-control" id="modal-category-description" name="description" rows="3" required></textarea>
                    </div>

                    <!-- Submit Button -->
                    <button type="submit" class="btn btn-success">Update Category</button>
                </form>

            </div>
        </div>
    </div>
</div>
</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
<script>
    // JavaScript to populate the modal with dynamic data
    document.querySelectorAll('.edit-btn').forEach(button => {
        button.addEventListener('click', function () {
            const id = this.getAttribute('data-id');
            const name = this.getAttribute('data-name');
            const description = this.getAttribute('data-description');
            const image = this.getAttribute('data-image');

            document.getElementById('modal-category-id').value = id;
            document.getElementById('modal-category-name').value = name;
            document.getElementById('modal-category-description').value = description;
            document.getElementById('modal-current-image').src = 'images/categories/' + image;
            document.getElementById('current-image-path').value = image;
        });
    });

    // Preview image before upload
    function previewImage(input, imageElement) {
        if (input.files && input.files[0]) {
            const reader = new FileReader();
            reader.onload = function(e) {
                imageElement.src = e.target.result;
            };
            reader.readAsDataURL(input.files[0]);
        }
    }

    // Add preview listeners
    document.getElementById('image').addEventListener('change', function() {
        previewImage(this, document.getElementById('preview-image'));
    });

    document.getElementById('modal-category-image').addEventListener('change', function() {
        previewImage(this, document.getElementById('modal-current-image'));
    });

    document.querySelectorAll('.edit-btn').forEach(button => {
        button.addEventListener('click', function () {
            const id = this.getAttribute('data-id');
            const name = this.getAttribute('data-name');
            const description = this.getAttribute('data-description');

            // Populate modal fields
            document.getElementById('modal-category-id').value = id;
            document.getElementById('modal-category-name').value = name;
            document.getElementById('modal-category-description').value = description;
        });
    });



</script>
</body>
</html>
